# encoding: utf-8
default: &settings 
  title: equipengine
  host: loc.my
  protocol: http
  port: 4500
  ip: 127.0.0.1
  error_email: 'info@equipengine.com'
  admin_email: 'info@equipengine.com'
  from_email: 'noreply@equipengine.com'

  api:
    jwt:
      token_days_live: 365
      secret: '9!}$69!}$692|:ME8,(v<;.cr]T/Ms+8m<njDb|:ME8,yW2693W'
      algorithm: HS256 
  
  sproutvideo:
    token_minutes_live: 300

  google_api:
    key: AIzaSyDjPPZbG6D8StmeqRUtI5rvSZRrwHlcEBk
test:
  <<: *settings
  host: example.com

development:
  <<: *settings

staging:
  <<: *settings

production:
  <<: *settings
  host: equipengine.com
  port: 443
