default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: equ110718
  # username: equipengine
  # password: equipengine

test:
  <<: *default
  database: equipengine_test

staging:
  <<: *default

production:
  <<: *default
