user:
  statuses:
    active: Active
    suspended: Suspended
    deleted: Deleted

  admin_roles:
    super_admin: Super Admin

organization_user:
  roles:
    student: Student
    teacher: Teacher
    admin: Admin

group:
  statuses:
    active: Active
    pause: Pause
  
  visibilities:
    private: Private
    public: Public

actions:
  action_types:
    reading: Reading
    question: Question
    watch: Watch