user:
  statuses:
    active: Active
    suspended: Suspended
    deleted: Deleted

  admin_roles:
    simple: Simple
    super_admin: Super Admin

organization_user:
  roles:
    student: Student
    teacher: Teacher
    admin: Admin

  statuses:
    active: Active
    suspended: Suspended

group:
  statuses:
    active: Active
    pause: Pause
  
  visibilities:
    private: Private
    public: Public

group_user:
  statuses:
    active: Active
    pause: Pause

task:
  action_types:
    reading: Reading
    question: Question
    watch: Watch

task_user:
  statuses:
    active: Active
    completed: Completed

course_group:
  complete_lesson_cans:
    teacher: Teacher
    student: Student
    all: All

  statuses:
    active: Active
    pause: Pause

lesson:
  statuses:
    active: Active
    pause: Pause

lesson_user:
  statuses:
    active: Active
    completed: Completed

course_user:
  statuses:
    active: Active
    disabled: Disabled
    in_progress: In Progress
    completed: Completed

video:
  statuses:
    draft: Draft
    processing: Processing
    ready: Ready
    failed: Failed

  sproutvideo:
    states:
      Deployed: ready
      Processing: processing
      Inspecting: draft
      Failed: failed

activity:
  statuses:
    pending: In queue
    sent: Sent
    read: Read
